
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Lockstep.Math;                                                                             
using Unity.Burst;                                                                               
using Unity.Mathematics;                                                                                                                                                                            
namespace GamesTan.ECS.Game {  
    public unsafe class NativePoolPClassA :NativeEntityPool<PClassA>{
    }
    public unsafe class NativePoolSubClassA :NativeEntityPool<SubClassA>{
    }
    public unsafe class NativePoolSubClassB :NativeEntityPool<SubClassB>{
    }
    public unsafe class NativePoolEnemy :NativeEntityPool<Enemy>{
    }
    public unsafe class NativePoolBullet :NativeEntityPool<Bullet>{
    }
    public unsafe class NativePoolBulletEmitter :NativeEntityPool<BulletEmitter>{
    } 
}


                                                                                                                                                                                                                                                                                     