
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            
namespace GamesTan.ECS.Game {
    using Lockstep.Game;
    public partial class Context {
        protected Context _context; 
   
        protected IGameStateService _gameStateService;    
        protected override void OnAwake(BaseContext context, IServiceContainer services){
            _context =  (Context) context;
            //BuildInServices
 
            //GameServices
            _gameStateService = services.GetService<IGameStateService>(); 
        }
    }
    public partial class GameBaseSystem {
        protected Context _context; 
   
        protected IGameStateService _gameStateService;    
        protected override void OnAwake(BaseContext context, IServiceContainer services){
            _context =  (Context) context;
            //BuildInServices
 
            //GameServices
            _gameStateService = services.GetService<IGameStateService>(); 
        }
    }
    public partial class GameJobSystem {
        protected Context _context; 
   
        protected IGameStateService _gameStateService;    
        protected override void OnAwake(BaseContext context, IServiceContainer services){
            _context =  (Context) context;
            //BuildInServices
 
            //GameServices
            _gameStateService = services.GetService<IGameStateService>(); 
        }
    }
    public partial class GameExecuteSystem {
        protected Context _context; 
   
        protected IGameStateService _gameStateService;    
        protected override void OnAwake(BaseContext context, IServiceContainer services){
            _context =  (Context) context;
            //BuildInServices
 
            //GameServices
            _gameStateService = services.GetService<IGameStateService>(); 
        }
    } 
}                                                                                                                                                                                                                                                                                     