
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            
namespace GamesTan.ECS.Game {  
    public static unsafe partial class EntityUtil {
        public static Enemy* CastToEnemy(Entity* entity){
            if (entity != null && entity->_ref._type == EntityIds.Enemy) {
                return (Enemy*) entity;
            }
            return null;
        }
        public static Bullet* CastToBullet(Entity* entity){
            if (entity != null && entity->_ref._type == EntityIds.Bullet) {
                return (Bullet*) entity;
            }
            return null;
        }
        public static BulletEmitter* CastToBulletEmitter(Entity* entity){
            if (entity != null && entity->_ref._type == EntityIds.BulletEmitter) {
                return (BulletEmitter*) entity;
            }
            return null;
        } 
        public static object ToBoxedStruct(Entity* entity){
            if (entity == null) {
                return null;
            }
            switch (entity->_ref._type) {
                case EntityIds.Enemy: return (object) (*((Enemy*) entity));
                case EntityIds.Bullet: return (object) (*((Bullet*) entity));
                case EntityIds.BulletEmitter: return (object) (*((BulletEmitter*) entity)); 
            }

            return null;
        }
    }
}
                                                                                                                                                                                                                                                                                     