
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            
namespace GamesTan.ECS.Game {  
    public unsafe partial struct _DefaultDefine {
        //enum 
        public static EEntityType EEntityType;
        public static ECampType ECampType;
        public static EItemType EItemType;
        public static EDir EDir;
        //IRef 
  
        //IEntity 
        public static Enemy Enemy;
        public static Bullet Bullet;
        public static BulletEmitter BulletEmitter;  
        //IAsset 
 
        //IComponent  
        public static MeshRenderData MeshRenderData;
        public static AnimRenderData AnimRenderData;
        public static PhysicData PhysicData;
        public static BasicData BasicData;
        public static EnemyTag EnemyTag;
        public static BulletTag BulletTag;
        public static SpawnerTag SpawnerTag;
        public static UnitData UnitData;
        public static EmitterData EmitterData;
        public static AIData AIData;
        public static AnimData AnimData;
        public static Animator Animator;
        public static CollisionAgent CollisionAgent;
        public static NavMeshAgent NavMeshAgent;
        public static AssetData AssetData;
        public static Transform2D Transform2D;
        public static Transform3D Transform3D; 

    }
}                                                                                                                                                                                                                                                                                     