
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            
namespace GamesTan.ECS.Game {  
    using Lockstep.Game;    
    using NetMsg.Common;

    public unsafe partial class TempFields {
        private Context _context;
        public Dictionary<int, InputCmd> InputCmds = new Dictionary<int, InputCmd>();

        public TempFields(Context context){
            this._context = context;
        }
    }

    public unsafe partial class Context : BaseContext {
        private static Context _instance;
        public static Context Instance {
            get => _instance ?? (_instance = new Context());
            set => _instance = value;
        }
        public bool HasInit = false;
        public TempFields TempFields{ get;private set;}

        public _EntityManager _entities = new _EntityManager();
        public IEntityService _entityService;
        private IServiceContainer _services;
        public T GetService<T>() where T : Lockstep.Game.IService{
            if (_services == null) return default(T);
            return _services.GetService<T>();
        }


    #region Rollback Implement
        private ClassBackupHelper<_EntityManager> _entitiesBackuper = new ClassBackupHelper<_EntityManager>();

        protected override void _DoBackup(int tick){
            _entitiesBackuper.Backup(tick, _entities.Clone());
        }

        protected override void _DoRollbackTo(int tick, int missFrameTick, bool isNeedClear){
            var clone = _entitiesBackuper.RollbackTo(tick, missFrameTick, isNeedClear);
            clone.CopyTo(_entities);
        }

        protected override void _DoCleanUselessSnapshot(int checkedTick){
            _entitiesBackuper.CleanUselessSnapshot(checkedTick,(es)=>es.Free());
        }
    #endregion
    #region Lifecycle
        private FuncOnEntityCreated<Enemy> funcOnCreateEntityEnemy;
        private FuncOnEntityCreated<Enemy> funcResetEntityEnemy;
        private FuncOnEntityCreated<Bullet> funcOnCreateEntityBullet;
        private FuncOnEntityCreated<Bullet> funcResetEntityBullet;
        private FuncOnEntityCreated<BulletEmitter> funcOnCreateEntityBulletEmitter;
        private FuncOnEntityCreated<BulletEmitter> funcResetEntityBulletEmitter; 
 

        protected override void _DoAwake(IServiceContainer services){            
            RegisterSystemFunctions();
            TempFields = new TempFields(this);
            OnAwake(this,services);
            _entities.Alloc();
            _services = services;
            // reduce gc
            funcOnCreateEntityEnemy = OnEntityCreatedEnemy;
            funcResetEntityEnemy = ResetEntityEnemy;
            funcOnCreateEntityBullet = OnEntityCreatedBullet;
            funcResetEntityBullet = ResetEntityBullet;
            funcOnCreateEntityBulletEmitter = OnEntityCreatedBulletEmitter;
            funcResetEntityBulletEmitter = ResetEntityBulletEmitter; 
        }
        protected override void _DoDestroy(){
            //TempFields.OnDestroy();
            _entities.Free();
        }
        protected override void _BeforeSchedule(){
            //TempFields.FramePrepare();
        }
        protected override void _AfterSchedule(){
            //TempFields.FrameClearUp();
        }


        protected override void _DoDestroyEntity(EntityRef entityRef){
            DestroyEntityInternal(GetEntity(entityRef));
        }
        
        public Entity* GetEntity(int entityId) {
            if (_id2EntityRef.TryGetValue(entityId, out var entityRef)) {
                var ptr = GetEntity(entityRef);
                return ptr;
            }
            return null;
        }
        public Entity* GetEntity(EntityRef entityRef){
            switch (entityRef._type) {
                case EntityIds.Enemy: return (Entity*) GetEnemy(entityRef);
                case EntityIds.Bullet: return (Entity*) GetBullet(entityRef);
                case EntityIds.BulletEmitter: return (Entity*) GetBulletEmitter(entityRef); 
            }
            return null;
        }

        private void DestroyEntityInternal(Entity* entity){
            if (entity == null) {
                return;
            }

            if (entity->_active == false) {
                return;
            }

            switch (entity->_ref._type) {
                case EntityIds.Enemy:
                    DestroyEnemyInternal((Enemy*) entity);
                    break;
                case EntityIds.Bullet:
                    DestroyBulletInternal((Bullet*) entity);
                    break;
                case EntityIds.BulletEmitter:
                    DestroyBulletEmitterInternal((BulletEmitter*) entity);
                    break; 
            }
        }
  
        private unsafe void PostUpdateCreateEnemy(){
            _entities._EnemyAry.PostUpdateCreate(funcOnCreateEntityEnemy,funcResetEntityEnemy);
        }
        private unsafe void PostUpdateCreateBullet(){
            _entities._BulletAry.PostUpdateCreate(funcOnCreateEntityBullet,funcResetEntityBullet);
        }
        private unsafe void PostUpdateCreateBulletEmitter(){
            _entities._BulletEmitterAry.PostUpdateCreate(funcOnCreateEntityBulletEmitter,funcResetEntityBulletEmitter);
        } 

    #endregion
    #region Entity Enemy
        private void OnEntityCreatedEnemy(Enemy* dstPtr){
            _EntityCreated(&dstPtr->_entity);
            _entityService.OnEntityCreated(this, (Entity*) dstPtr);
            _entityService.OnEnemyCreated(this, dstPtr);
        }

        private void ResetEntityEnemy(Enemy* dstPtr){
            *dstPtr = _DefaultDefine.Enemy;
        }
        public Boolean EnemyExists(EntityRef entityRef){
            return GetEnemy(entityRef) != null;
        }

        public Enemy* PostCmdCreateEnemy(){
            return _entities.CreateTempEnemy(this);
        }

        private void DestroyEnemyInternal(Enemy* ptr){
            _entities._EnemyAry.ReleaseEntity((Entity*)ptr);
            _entityService.OnEnemyDestroy(this, ptr);
            _entityService.OnEntityDestroy(this, &ptr->_entity);
            var copy = ptr->_entity;
            *ptr = _DefaultDefine.Enemy;
            ptr->_entity = copy;
            _EntityDestroy(&ptr->_entity);
        }

        public void DestroyEnemy(Enemy* ptr){
            if (ptr == null) {
                return;
            }

            if (ptr->_entity._active == false) {
                return;
            }

            _destroy.Enqueue(ptr->EntityRef);
        }

        public void DestroyEnemy(EntityRef entityRef){
            _destroy.Enqueue(entityRef);
        }
    #endregion
    #region Entity Bullet
        private void OnEntityCreatedBullet(Bullet* dstPtr){
            _EntityCreated(&dstPtr->_entity);
            _entityService.OnEntityCreated(this, (Entity*) dstPtr);
            _entityService.OnBulletCreated(this, dstPtr);
        }

        private void ResetEntityBullet(Bullet* dstPtr){
            *dstPtr = _DefaultDefine.Bullet;
        }
        public Boolean BulletExists(EntityRef entityRef){
            return GetBullet(entityRef) != null;
        }

        public Bullet* PostCmdCreateBullet(){
            return _entities.CreateTempBullet(this);
        }

        private void DestroyBulletInternal(Bullet* ptr){
            _entities._BulletAry.ReleaseEntity((Entity*)ptr);
            _entityService.OnBulletDestroy(this, ptr);
            _entityService.OnEntityDestroy(this, &ptr->_entity);
            var copy = ptr->_entity;
            *ptr = _DefaultDefine.Bullet;
            ptr->_entity = copy;
            _EntityDestroy(&ptr->_entity);
        }

        public void DestroyBullet(Bullet* ptr){
            if (ptr == null) {
                return;
            }

            if (ptr->_entity._active == false) {
                return;
            }

            _destroy.Enqueue(ptr->EntityRef);
        }

        public void DestroyBullet(EntityRef entityRef){
            _destroy.Enqueue(entityRef);
        }
    #endregion
    #region Entity BulletEmitter
        private void OnEntityCreatedBulletEmitter(BulletEmitter* dstPtr){
            _EntityCreated(&dstPtr->_entity);
            _entityService.OnEntityCreated(this, (Entity*) dstPtr);
            _entityService.OnBulletEmitterCreated(this, dstPtr);
        }

        private void ResetEntityBulletEmitter(BulletEmitter* dstPtr){
            *dstPtr = _DefaultDefine.BulletEmitter;
        }
        public Boolean BulletEmitterExists(EntityRef entityRef){
            return GetBulletEmitter(entityRef) != null;
        }

        public BulletEmitter* PostCmdCreateBulletEmitter(){
            return _entities.CreateTempBulletEmitter(this);
        }

        private void DestroyBulletEmitterInternal(BulletEmitter* ptr){
            _entities._BulletEmitterAry.ReleaseEntity((Entity*)ptr);
            _entityService.OnBulletEmitterDestroy(this, ptr);
            _entityService.OnEntityDestroy(this, &ptr->_entity);
            var copy = ptr->_entity;
            *ptr = _DefaultDefine.BulletEmitter;
            ptr->_entity = copy;
            _EntityDestroy(&ptr->_entity);
        }

        public void DestroyBulletEmitter(BulletEmitter* ptr){
            if (ptr == null) {
                return;
            }

            if (ptr->_entity._active == false) {
                return;
            }

            _destroy.Enqueue(ptr->EntityRef);
        }

        public void DestroyBulletEmitter(EntityRef entityRef){
            _destroy.Enqueue(entityRef);
        }
    #endregion 

    #region GetEntity
        private EnemyIterator GetAllEnemy(){
            return new EnemyIterator(_entities.GetEnemy(0),_entities.MaxEnemyIndex + 1);
        }
        private BulletIterator GetAllBullet(){
            return new BulletIterator(_entities.GetBullet(0),_entities.MaxBulletIndex + 1);
        }
        private BulletEmitterIterator GetAllBulletEmitter(){
            return new BulletEmitterIterator(_entities.GetBulletEmitter(0),_entities.MaxBulletEmitterIndex + 1);
        } 

        private EntityFilter[] GetAllEntities(){
            var all = new EntityFilter[_entities.CurTotalEntityCount];
            var count = 0;
            {
                var ptr = _entities.GetEnemy(0);
                var len = _entities._EnemyAry.Length;
                for (var i = 0; i < len; ++i, ++ptr) {
                    all[count++].Entity = &ptr->_entity;
                }
            }
            {
                var ptr = _entities.GetBullet(0);
                var len = _entities._BulletAry.Length;
                for (var i = 0; i < len; ++i, ++ptr) {
                    all[count++].Entity = &ptr->_entity;
                }
            }
            {
                var ptr = _entities.GetBulletEmitter(0);
                var len = _entities._BulletEmitterAry.Length;
                for (var i = 0; i < len; ++i, ++ptr) {
                    all[count++].Entity = &ptr->_entity;
                }
            } 
            return all;
        }
    #endregion
#if false // TODO fixed buildin components
    #region GetBuildInComponet
        public unsafe Buffer<MeshRenderDataFilter> GetAllMeshRenderData()
        {
            Buffer<MeshRenderDataFilter> buffer = Buffer<MeshRenderDataFilter>.Alloc(_entities.CurTotalEntityCount);
            Bullet* BulletPtr = this._entities.GetBullet(0);
            var idxBullet = 1;
            while (idxBullet >= 0)
            {
                if (BulletPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletPtr->_entity;
                  buffer.Items[buffer.Count].MeshRenderData = &BulletPtr->MeshRenderData;
                  ++buffer.Count;
                }
                --idxBullet;
                ++BulletPtr;
            }
            BulletEmitter* BulletEmitterPtr = this._entities.GetBulletEmitter(0);
            var idxBulletEmitter = 1;
            while (idxBulletEmitter >= 0)
            {
                if (BulletEmitterPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletEmitterPtr->_entity;
                  buffer.Items[buffer.Count].MeshRenderData = &BulletEmitterPtr->MeshRenderData;
                  ++buffer.Count;
                }
                --idxBulletEmitter;
                ++BulletEmitterPtr;
            } 
            return buffer;
        }
        public unsafe Buffer<AnimRenderDataFilter> GetAllAnimRenderData()
        {
            Buffer<AnimRenderDataFilter> buffer = Buffer<AnimRenderDataFilter>.Alloc(_entities.CurTotalEntityCount);
            Enemy* EnemyPtr = this._entities.GetEnemy(0);
            var idxEnemy = 1;
            while (idxEnemy >= 0)
            {
                if (EnemyPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &EnemyPtr->_entity;
                  buffer.Items[buffer.Count].AnimRenderData = &EnemyPtr->AnimRenderData;
                  ++buffer.Count;
                }
                --idxEnemy;
                ++EnemyPtr;
            } 
            return buffer;
        }
        public unsafe Buffer<PhysicDataFilter> GetAllPhysicData()
        {
            Buffer<PhysicDataFilter> buffer = Buffer<PhysicDataFilter>.Alloc(_entities.CurTotalEntityCount);
            Enemy* EnemyPtr = this._entities.GetEnemy(0);
            var idxEnemy = 1;
            while (idxEnemy >= 0)
            {
                if (EnemyPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &EnemyPtr->_entity;
                  buffer.Items[buffer.Count].PhysicData = &EnemyPtr->PhysicData;
                  ++buffer.Count;
                }
                --idxEnemy;
                ++EnemyPtr;
            }
            Bullet* BulletPtr = this._entities.GetBullet(0);
            var idxBullet = 1;
            while (idxBullet >= 0)
            {
                if (BulletPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletPtr->_entity;
                  buffer.Items[buffer.Count].PhysicData = &BulletPtr->PhysicData;
                  ++buffer.Count;
                }
                --idxBullet;
                ++BulletPtr;
            }
            BulletEmitter* BulletEmitterPtr = this._entities.GetBulletEmitter(0);
            var idxBulletEmitter = 1;
            while (idxBulletEmitter >= 0)
            {
                if (BulletEmitterPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletEmitterPtr->_entity;
                  buffer.Items[buffer.Count].PhysicData = &BulletEmitterPtr->PhysicData;
                  ++buffer.Count;
                }
                --idxBulletEmitter;
                ++BulletEmitterPtr;
            } 
            return buffer;
        }
        public unsafe Buffer<BasicDataFilter> GetAllBasicData()
        {
            Buffer<BasicDataFilter> buffer = Buffer<BasicDataFilter>.Alloc(_entities.CurTotalEntityCount);
            Enemy* EnemyPtr = this._entities.GetEnemy(0);
            var idxEnemy = 1;
            while (idxEnemy >= 0)
            {
                if (EnemyPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &EnemyPtr->_entity;
                  buffer.Items[buffer.Count].BasicData = &EnemyPtr->BasicData;
                  ++buffer.Count;
                }
                --idxEnemy;
                ++EnemyPtr;
            }
            Bullet* BulletPtr = this._entities.GetBullet(0);
            var idxBullet = 1;
            while (idxBullet >= 0)
            {
                if (BulletPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletPtr->_entity;
                  buffer.Items[buffer.Count].BasicData = &BulletPtr->BasicData;
                  ++buffer.Count;
                }
                --idxBullet;
                ++BulletPtr;
            }
            BulletEmitter* BulletEmitterPtr = this._entities.GetBulletEmitter(0);
            var idxBulletEmitter = 1;
            while (idxBulletEmitter >= 0)
            {
                if (BulletEmitterPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletEmitterPtr->_entity;
                  buffer.Items[buffer.Count].BasicData = &BulletEmitterPtr->BasicData;
                  ++buffer.Count;
                }
                --idxBulletEmitter;
                ++BulletEmitterPtr;
            } 
            return buffer;
        }
        public unsafe Buffer<AnimatorFilter> GetAllAnimator()
        {
            Buffer<AnimatorFilter> buffer = Buffer<AnimatorFilter>.Alloc(_entities.CurTotalEntityCount);
 
            return buffer;
        }
        public unsafe Buffer<CollisionAgentFilter> GetAllCollisionAgent()
        {
            Buffer<CollisionAgentFilter> buffer = Buffer<CollisionAgentFilter>.Alloc(_entities.CurTotalEntityCount);
 
            return buffer;
        }
        public unsafe Buffer<NavMeshAgentFilter> GetAllNavMeshAgent()
        {
            Buffer<NavMeshAgentFilter> buffer = Buffer<NavMeshAgentFilter>.Alloc(_entities.CurTotalEntityCount);
 
            return buffer;
        }
        public unsafe Buffer<AssetDataFilter> GetAllAssetData()
        {
            Buffer<AssetDataFilter> buffer = Buffer<AssetDataFilter>.Alloc(_entities.CurTotalEntityCount);
            Enemy* EnemyPtr = this._entities.GetEnemy(0);
            var idxEnemy = 1;
            while (idxEnemy >= 0)
            {
                if (EnemyPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &EnemyPtr->_entity;
                  buffer.Items[buffer.Count].AssetData = &EnemyPtr->AssetData;
                  ++buffer.Count;
                }
                --idxEnemy;
                ++EnemyPtr;
            }
            Bullet* BulletPtr = this._entities.GetBullet(0);
            var idxBullet = 1;
            while (idxBullet >= 0)
            {
                if (BulletPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletPtr->_entity;
                  buffer.Items[buffer.Count].AssetData = &BulletPtr->AssetData;
                  ++buffer.Count;
                }
                --idxBullet;
                ++BulletPtr;
            }
            BulletEmitter* BulletEmitterPtr = this._entities.GetBulletEmitter(0);
            var idxBulletEmitter = 1;
            while (idxBulletEmitter >= 0)
            {
                if (BulletEmitterPtr->_entity._active)
                {
                  buffer.Items[buffer.Count].Entity = &BulletEmitterPtr->_entity;
                  buffer.Items[buffer.Count].AssetData = &BulletEmitterPtr->AssetData;
                  ++buffer.Count;
                }
                --idxBulletEmitter;
                ++BulletEmitterPtr;
            } 
            return buffer;
        }
        public unsafe Buffer<Transform2DFilter> GetAllTransform2D()
        {
            Buffer<Transform2DFilter> buffer = Buffer<Transform2DFilter>.Alloc(_entities.CurTotalEntityCount);
 
            return buffer;
        }
        public unsafe Buffer<Transform3DFilter> GetAllTransform3D()
        {
            Buffer<Transform3DFilter> buffer = Buffer<Transform3DFilter>.Alloc(_entities.CurTotalEntityCount);
 
            return buffer;
        } 
    #endregion
#endif

    }
}                                                                                                                                                                                                                                                                                     