
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Lockstep.Math;                                                                             
using Unity.Burst;                                                                               
using Unity.Mathematics;                                                                                                                                                                            

namespace GamesTan.ECS.Game {  
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct PClassA :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public int Val1; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct SubClassA :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public int Val1;
        public LFloat Val2; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct SubClassB :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public int Val1;
        public long Val3; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct SubClassBC :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public int Val1;
        public long Val3;
        public uint Val4; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Enemy :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public EnemyTag EnemyTag;
        public UnitData UnitData;
        public AIData AIData;
        public AnimRenderData AnimRenderData;
        public AnimData AnimData; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Bullet :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public BulletTag BulletTag;
        public MeshRenderData MeshRenderData;
        public UnitData UnitData; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct BulletEmitter :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData;
        public SpawnerTag SpawnerTag;
        public MeshRenderData MeshRenderData;
        public EmitterData EmitterData; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public LFloat DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public LVector3 Forward {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector3(LMath.Cos(deg), 0, LMath.Sin(deg));
            }
        }

        public LVector2 Forward2 {
            get {
                LFloat deg = LMath.Deg2Rad*(-DegY + 90);
                return new LVector2(LMath.Cos(deg), LMath.Sin(deg));
            }
        }
        public LFloat Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public LVector3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public LVector3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public LVector3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public LFloat Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new LVector3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    } 

}
                                                                                                                                                                                                                                                                                     