
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            
namespace GamesTan.ECS.Game {  
#if true
   public static unsafe class PointerExt {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Enemy* ToEnemyPtr(this long val){
            #if DEBUG
            if ((val == 0L || ((Enemy*) val)->EntityType != EEntityType.Enemy)) {
                throw new Exception("ToEnemyPtr error: diff type " + val);
            }
            #endif
            return (Enemy*) val;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Bullet* ToBulletPtr(this long val){
            #if DEBUG
            if ((val == 0L || ((Bullet*) val)->EntityType != EEntityType.Bullet)) {
                throw new Exception("ToBulletPtr error: diff type " + val);
            }
            #endif
            return (Bullet*) val;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static BulletEmitter* ToBulletEmitterPtr(this long val){
            #if DEBUG
            if ((val == 0L || ((BulletEmitter*) val)->EntityType != EEntityType.BulletEmitter)) {
                throw new Exception("ToBulletEmitterPtr error: diff type " + val);
            }
            #endif
            return (BulletEmitter*) val;
        } 
    }

    [StructLayoutAttribute(LayoutKind.Sequential, Pack = Define.PackSize)]
    public unsafe partial struct EnemyIterator : IEnumerator<long>, IEnumerable<long> {
        private Int32 _index;
        private Enemy* _ptr;
        private long _current;
        private int _count;
        public long Current => _current;
        object IEnumerator.Current {
            get { return (object) Current; }
        }
        IEnumerator IEnumerable.GetEnumerator(){
            return this;
        }
        public IEnumerator<long> GetEnumerator(){
            return this;
        }

        public EnemyIterator(Enemy* ptr,int count){
            _ptr = ptr;
            _index = -1;
            _current = 0;
            _count = count;
        }

        public Boolean MoveNext(){
            while (++_index < _count) {
                if (_ptr[_index]._entity._active) {
                    _current = (long) (&_ptr[_index]);
                    return true;
                }
            }
            _current = 0;
            return false;
        }

        public void Reset(){
            _index = -1;
            _current = 0;
        }
        public void Dispose(){ }
    }
    [StructLayoutAttribute(LayoutKind.Sequential, Pack = Define.PackSize)]
    public unsafe partial struct BulletIterator : IEnumerator<long>, IEnumerable<long> {
        private Int32 _index;
        private Bullet* _ptr;
        private long _current;
        private int _count;
        public long Current => _current;
        object IEnumerator.Current {
            get { return (object) Current; }
        }
        IEnumerator IEnumerable.GetEnumerator(){
            return this;
        }
        public IEnumerator<long> GetEnumerator(){
            return this;
        }

        public BulletIterator(Bullet* ptr,int count){
            _ptr = ptr;
            _index = -1;
            _current = 0;
            _count = count;
        }

        public Boolean MoveNext(){
            while (++_index < _count) {
                if (_ptr[_index]._entity._active) {
                    _current = (long) (&_ptr[_index]);
                    return true;
                }
            }
            _current = 0;
            return false;
        }

        public void Reset(){
            _index = -1;
            _current = 0;
        }
        public void Dispose(){ }
    }
    [StructLayoutAttribute(LayoutKind.Sequential, Pack = Define.PackSize)]
    public unsafe partial struct BulletEmitterIterator : IEnumerator<long>, IEnumerable<long> {
        private Int32 _index;
        private BulletEmitter* _ptr;
        private long _current;
        private int _count;
        public long Current => _current;
        object IEnumerator.Current {
            get { return (object) Current; }
        }
        IEnumerator IEnumerable.GetEnumerator(){
            return this;
        }
        public IEnumerator<long> GetEnumerator(){
            return this;
        }

        public BulletEmitterIterator(BulletEmitter* ptr,int count){
            _ptr = ptr;
            _index = -1;
            _current = 0;
            _count = count;
        }

        public Boolean MoveNext(){
            while (++_index < _count) {
                if (_ptr[_index]._entity._active) {
                    _current = (long) (&_ptr[_index]);
                    return true;
                }
            }
            _current = 0;
            return false;
        }

        public void Reset(){
            _index = -1;
            _current = 0;
        }
        public void Dispose(){ }
    } 

#endif
}
                                                                                                                                                                                                                                                                                     