
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            
namespace Lockstep.Game {  
    using GamesTan.ECS;
    using GamesTan.ECS.Game;
    public unsafe partial interface IGameEventService : IService{
    
    } 
    public unsafe partial class PureGameEventService : IGameEventService{
    
    } 
}
namespace GamesTan.ECS.Game {
    using Lockstep.Game;
    public unsafe partial class GameBaseSystem {
      
    }
    public unsafe partial class GameExecuteSystem {
      
    } 


}                                                                                                                                                                                                                                                                                     