
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/GamesTanEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using Lockstep.UnsafeECS;                                                                        
using Unity.Burst;                                                                               
using Unity.Mathematics;                                                                         
namespace GamesTan.ECS.Game{                                                                          
    public unsafe partial struct __default {
        //IRef 
  
        //IEntity 
        public static Enemy Enemy;
        public static Bullet Bullet;
        public static BulletEmitter BulletEmitter;  
        //IAsset 
 
        //IComponent  
        public static EnemyTag EnemyTag;
        public static BulletTag BulletTag;
        public static SpawnerTag SpawnerTag;
        public static UnitData UnitData;
        public static EmitterData EmitterData;
        public static AIData AIData;
        public static AnimData AnimData; 
        //Bitset  
 
    }                                                                                
}                                                                                               