
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by GamesTan.Tools.MacroExpansion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepECS                                         
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

//Power by ME //src: https://github.com/JiepengTan/ME  

//#define DONT_USE_GENERATE_CODE                                                                 
                                                                                                 
using System.Linq;                                                                               
using System.Runtime.InteropServices;                                                            
using System;                                                                                    
using System.Collections.Generic;                                                                
using System.Collections;                                                                        
using System.Runtime.CompilerServices;                                                           
using Lockstep.Game;                                                                             
using Unity.Burst;                                                                               
using Lockstep.Math;                                                                             
using Unity.Mathematics;                                                                                                                                                                            

namespace GamesTan.ECS.Game {  
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Enemy :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public EnemyTag EnemyTag;
        public UnitData UnitData;
        public AIData AIData;
        public AnimRenderData AnimRenderData;
        public AnimData AnimData;
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public float DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public float3 Forward {
            get {
                float deg = math.radians(-DegY + 90);
                return new float3(math.cos(deg), 0, math.sin(deg));
            }
        }

        public float2 Forward2 {
            get {
                float deg = math.radians(-DegY + 90);
                return new float2(math.cos(deg), math.sin(deg));
            }
        }
        public float Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public float3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public float3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public float3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public float Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new float3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Bullet :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public BulletTag BulletTag;
        public MeshRenderData MeshRenderData;
        public UnitData UnitData;
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public float DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public float3 Forward {
            get {
                float deg = math.radians(-DegY + 90);
                return new float3(math.cos(deg), 0, math.sin(deg));
            }
        }

        public float2 Forward2 {
            get {
                float deg = math.radians(-DegY + 90);
                return new float2(math.cos(deg), math.sin(deg));
            }
        }
        public float Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public float3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public float3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public float3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public float Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new float3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    }
    [System.Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct BulletEmitter :IEntity {

        public const Int32 INIT_COUNT = 1;
        public Entity _entity;
        public  void _SetEntityRef(EntityRef value) {
            _entity._ref = value;
        }
        public bool IsValid => _entity._active;
        // BuildIn properties
        public EntityRef EntityRef =>_entity._ref;
        public int EntityIndex =>_entity.EntityIndex;
        public EEntityType EntityType => (EEntityType)(_entity.TypeId);
        public bool IsActive =>_entity._active;
        public int EntityId => _entity._localId;

        // Fields
        public SpawnerTag SpawnerTag;
        public MeshRenderData MeshRenderData;
        public EmitterData EmitterData;
        public AssetData AssetData;
        public Transform3D TransformData;
        public BasicData BasicData;
        public PhysicData PhysicData; 

        /// <summary> GameObject Id   /// </summary>
        public int GObjectId {
            get => BasicData.GObjectId;
            set => BasicData.GObjectId = value;
        }
        
        /// <summary> 是否已经释放   /// </summary>
        public bool IsAlreadyStart {
            get => BasicData.StatusData.Is(0);
            set => BasicData.StatusData.Set(0, value);
        }

        /// <summary> 旋转   /// </summary>
        public float DegY {
            get => TransformData.Rotation.y;
            set => TransformData.Rotation.y = value;
        }

        public float3 Forward {
            get {
                float deg = math.radians(-DegY + 90);
                return new float3(math.cos(deg), 0, math.sin(deg));
            }
        }

        public float2 Forward2 {
            get {
                float deg = math.radians(-DegY + 90);
                return new float2(math.cos(deg), math.sin(deg));
            }
        }
        public float Radius {
            get => PhysicData.Radius;
            set => PhysicData.Radius = value;
        }
        public float3 Pos3 {
            get => TransformData.Position;
            set => TransformData.Position = value;
        }
        public float3 Rot3 {
            get => TransformData.Rotation;
            set => TransformData.Rotation = value;
        }
        public float3 Scale3 {
            get => TransformData.Scale;
            set => TransformData.Scale = value;
        }
        public float Scale {
            get => TransformData.Scale.x;
            set {
                TransformData.Scale = new float3(2, 2, 2) * value;
                PhysicData.Radius = value;
            }
        }

    } 

}
                                                                                                                                                                                                                                                                                     